mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    #url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/',include('polls.urls', namespace = "polls")),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$',views.index,name='index'),
	url(r'^(?P<question_id>[0-9]+)/$', views.detail, name= 'details'),
	url(r'^(?P<question_id>[0-9]+)/results/$', views.results,name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name = 'vote'),


]

polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('data published')

	def __str__(self):
		return self.question_text


class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=100)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

polls/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Choice, Question
from django.core.urlresolvers import reverse

# Create your views here.
def index(request):
	latest_question_list = Question.objects.order_by('-pub_date')[:5]
	#template = loader.get_template('polls/index.html')
	context = {
		'latest_question_list': latest_question_list,
	}
	#return HttpResponse(template.render(context,request))
	return render(request,'polls/index.html',context)


def detail(request,question_id):
	#try:
	#	question = Question.objects.get(pk=question_id)
	#except Question.DoesNotExist:
	#	raise Http404("Question does not exist")

	#return render(request,'polls/details.html',{'question': question})

	#return HttpResponse("You are looking at question %s" %question_id)
	question= get_object_or_404(Question,pk = question_id)
	return render(request,'polls/details.html',{'question': question})





def results(request,question_id):
	#r = "You are looking at the results of question %s"
	#return HttpResponse(r % question_id)
	question = get_object_or_404(Question,pk = question_id)
	return render(request, "polls/results.html", {'question': question})



def vote(request,question_id):
	#return HttpResponse("THe number of votes  for %s are  x"%question_id)
	p = get_object_or_404(Question, pk= question_id)
	try:
		selected_choice = p.choice_set.get(pk= request.POST['choice'])
	except (Keyerror, Choice.DoesNotExist):
		return render(request, polls/details.html,{
			'question': p,
			'error_message': "You didn't select a choice",
			})	
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse("polls:results", args=(p.id,)))

polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

<a href = {% url 'polls:index'%}>Back to Homepage</a>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:details' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text}} </h1>

<ul>
{% for choice in question.choice_set.all  %}
	<li> {{ choice.choice_text}} -- {{ choice.votes }} vote{{choice.votes|pluralize }}
{% endfor %}
</ul>

<a href = "{% url 'polls:details' question.id %}"> Vote Again? </a>